apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-hash-service
  labels:
    app: message-hash-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: message-hash-service
  template:
    metadata:
      labels:
        app: message-hash-service
    spec:
      serviceAccountName: {{ .Values.service_account_name }} #web-hash-service-svc
      containers:
      - name: message-hash-service
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: DYNAMODB_TABLE
          value: "MessageHashStore"
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: "regional"
        - name: AWS_EC2_METADATA_DISABLED
          value: "true"
